#!/bin/bash

# ...
./build/examples/cpp_classification/autoencoder.bin models/mnist_autoencoder/mnist_autoencoder_deploy.prototxt models/mnist_autoencoder/mnist_autoencoder_iter_65000.caffemodel examples/images/mnist-5.jpg
# ...
